apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-reaper
  name: cassandra-reaper
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: cassandra-reaper
---
apiVersion: v1
data:
  cassandra-reaper.yaml: |
    # Cassandra Reaper Configuration Example.
    # See a bit more complete example in:
    # src/test/resources/cassandra-reaper.yaml
    segmentCount: 200
    repairParallelism: DATACENTER_AWARE
    repairIntensity: 0.9
    scheduleDaysBetween: 7
    repairRunThreadCount: 15
    hangingRepairTimeoutMins: 30
    storageType: memory
    enableCrossOrigin: true
    incrementalRepair: false
    allowUnreachableNodes: false
    enableDynamicSeedList: true

    jmxPorts:
      127.0.0.1: 7100
      127.0.0.2: 7200
      127.0.0.3: 7300
      127.0.0.4: 7400
      127.0.0.5: 7500
      127.0.0.6: 7600
      127.0.0.7: 7700
      127.0.0.8: 7800

    logging:
      level: DEBUG
      loggers:
        io.dropwizard: DEBUG
        org.eclipse.jetty: DEBUG
      appenders:
        - type: console
          logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

    server:
      type: default
      applicationConnectors:
        - type: http
          port: 8080
          bindHost: 0.0.0.0
      adminConnectors:
        - type: http
          port: 8081
          bindHost: 0.0.0.0
      requestLog:
        appenders: []

    autoScheduling:
      enabled: false
      initialDelayPeriod: PT15S
      periodBetweenPolls: PT10M
      timeBeforeFirstSchedule: PT5M
      scheduleSpreadPeriod: PT6H
      excludedKeyspaces:
        - keyspace1
        - keyspace2
kind: ConfigMap
metadata:
  name: cassandra-reaper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cassandra-reaper
spec:
  serviceName: cassandra-reaper
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-reaper
    spec:

      volumes:
        - name: cassandra-reaper
          configMap:
            name: cassandra-reaper
            items:
            - key: cassandra-reaper.yaml
              path: cassandra-reaper.yaml

      containers:
      - name: cassandra-reaper
        image: mstump/cassandra-reaper:v0.5
        imagePullPolicy: Always
        volumeMounts:
        - name: cassandra-reaper
          mountPath: /etc/reaper
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: http-admin
        resources:
          limits:
            cpu: "100m"
            memory: 3Gi
          requests:
           cpu: "100m"
           memory: 3Gi
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
